matrix:
  include:
    - language: node_js
      node_js:
          - "12"
      install:
          - npm install -g vuepress
      script:
          - pyenv global system 3.6.7
          - pip3 install -e .
          - python3 docs/.vuepress/_reference/autogen.py
          - npm run docs:build
      cache:
          directories:
              - "node_modules"
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/.vuepress/dist
        github_token: $GITHUB_TOKEN
        repo: frthjf/machinable
        keep_history: true
        target_branch: gh-pages
        on:
          branch: master
    - language: python
      python:
        - 3.6
      install:
        - pip install -r test-requirements.txt
        - pip install --upgrade pytest
        - pip install -e .
      before_script: cd tests
      script:
        - pytest
notifications:
    email: false